import { jsPDF } from "jspdf";

interface AssessmentSection {
  name: string;
  score: string;
}

interface AssessmentReportPdfInput {
  assessmentName: string;
  courseName: string;
  date: string;
  score: string;
  status: string;
  totalQuestions: number;
  correctAnswers: number;
  accuracy: string;
  sections: AssessmentSection[];
}

export function downloadAssessmentReportPdf({
  assessmentName,
  courseName,
  date,
  score,
  status,
  totalQuestions,
  correctAnswers,
  accuracy,
  sections,
}: AssessmentReportPdfInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 44;

  const green: [number, number, number] = [20, 89, 63];
  const dark: [number, number, number] = [24, 35, 31];
  const muted: [number, number, number] = [102, 112, 105];
  const border: [number, number, number] = [222, 218, 206];

  doc.setFillColor(248, 250, 249);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setFillColor(...green);
  doc.rect(0, 0, pageWidth, 90, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text("CODO LMS", margin, 38);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Official Assessment Report", margin, 60);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(date, pageWidth - margin, 48, { align: "right" });

  let y = 120;

  doc.setDrawColor(...border);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 110, 12, 12, "FD");

  doc.setTextColor(...muted);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("ASSESSMENT", margin + 16, y + 24);
  doc.text("COURSE", margin + 16, y + 54);
  doc.text("FINAL SCORE", pageWidth / 2, y + 24);
  doc.text("STATUS", pageWidth / 2, y + 54);

  doc.setTextColor(...dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text(assessmentName, margin + 16, y + 40);
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(courseName, margin + 16, y + 72);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text(score, pageWidth / 2, y + 42);
  doc.setFontSize(12);
  doc.setTextColor(...green);
  doc.text(status, pageWidth / 2, y + 72);

  y += 138;

  doc.setTextColor(...dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Performance Metrics", margin, y);

  y += 14;
  doc.setDrawColor(...border);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 90, 10, 10, "S");

  const colWidth = (pageWidth - margin * 2) / 3;
  const incorrectAnswers = totalQuestions - correctAnswers;

  const metricRows = [
    { label: "TOTAL QUESTIONS", value: String(totalQuestions), x: margin + colWidth * 0.5 },
    { label: "CORRECT ANSWERS", value: String(correctAnswers), x: margin + colWidth * 1.5 },
    { label: "ACCURACY", value: accuracy, x: margin + colWidth * 2.5 },
  ];

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...muted);
  metricRows.forEach((metric) => {
    doc.text(metric.label, metric.x, y + 26, { align: "center" });
  });

  doc.setFontSize(22);
  doc.setTextColor(...dark);
  metricRows.forEach((metric) => {
    doc.text(metric.value, metric.x, y + 60, { align: "center" });
  });

  y += 122;
  doc.setTextColor(...dark);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Section-wise Scores", margin, y);

  y += 12;
  const rowHeight = 36;
  sections.forEach((section, index) => {
    doc.setDrawColor(...border);
    doc.roundedRect(margin, y + index * rowHeight, pageWidth - margin * 2, 30, 8, 8, "S");
    doc.setTextColor(...dark);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(section.name, margin + 14, y + 20 + index * rowHeight);
    doc.setFont("helvetica", "bold");
    doc.text(section.score, pageWidth - margin - 14, y + 20 + index * rowHeight, { align: "right" });
  });

  const footerY = pageHeight - 64;
  doc.setDrawColor(...border);
  doc.line(margin, footerY - 20, pageWidth - margin, footerY - 20);
  doc.setTextColor(...muted);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(
    `Incorrect Answers: ${incorrectAnswers}  |  Generated by CODO LMS`,
    margin,
    footerY,
  );

  doc.save(`${assessmentName.replace(/\s+/g, "-").toLowerCase()}-report.pdf`);
}
